// <auto-generated />
namespace Student_Management_systems.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class s : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(s));
        
        string IMigrationMetadata.Id
        {
            get { return "202006132127334_s"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
