// <auto-generated />
namespace Student_Management_systems.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class plsfixs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(plsfixs));
        
        string IMigrationMetadata.Id
        {
            get { return "202006131300308_plsfixs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
