// <auto-generated />
namespace Student_Management_systems.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DropTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropTables));
        
        string IMigrationMetadata.Id
        {
            get { return "202006130159178_DropTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
